### ISSUE TITLE
Using Measurements and DiffEqBase results in error

### ISSUE THREAD

**Issue by tkoolen** [JuliaDiffEq/DiffEqBase.jl#151]
On Julia 1.0:

```julia
julia> using Measurements
[ Info: Recompiling stale cache file /home/twan/.julia/compiled/v1.0/Measurements/8B0my.ji for Measurements [eff96d63-e80a-5855-80a2-b1b0885c5ab7]

julia> using DiffEqBase
┌ Warning: Error requiring Measurements from DiffEqBase:
│ UndefVarError: Measurement not defined
│ Stacktrace:
│  [1] top-level scope at /home/twan/.julia/packages/DiffEqBase/YSk7M/src/init.jl:20
│  [2] eval at ./boot.jl:319 [inlined]
│  [3] eval at /home/twan/.julia/packages/DiffEqBase/YSk7M/src/DiffEqBase.jl:1 [inlined]
│  [4] (::getfield(DiffEqBase, Symbol("##440#449")))() at /home/twan/.julia/packages/Requires/9Jse/src/require.jl:67
│  [5] err(::getfield(DiffEqBase, Symbol("##440#449")), ::Module, ::String) at /home/twan/.julia/packages/Requires/9Jse/src/require.jl:38
│  [6] #439 at /home/twan/.julia/packages/Requires/9Jse/src/require.jl:66 [inlined]
│  [7] withpath(::getfield(DiffEqBase, Symbol("##439#448")), ::String) at /home/twan/.julia/packages/Requires/9Jse/src/require.jl:28
│  [8] #438 at /home/twan/.julia/packages/Requires/9Jse/src/require.jl:65 [inlined]
│  [9] listenpkg(::getfield(DiffEqBase, Symbol("##438#447")), ::Base.PkgId) at /home/twan/.julia/packages/Requires/9Jse/src/require.jl:13
│  [10] macro expansion at /home/twan/.julia/packages/Requires/9Jse/src/require.jl:63 [inlined] (repeats 2 times)
│  [11] __init__() at /home/twan/.julia/packages/DiffEqBase/YSk7M/src/init.jl:2
│  [12] _include_from_serialized(::String, ::Array{Any,1}) at ./loading.jl:627
│  [13] macro expansion at ./logging.jl:312 [inlined]
│  [14] _require_search_from_serialized(::Base.PkgId, ::String) at ./loading.jl:698
│  [15] _require(::Base.PkgId) at ./loading.jl:931
│  [16] require(::Base.PkgId) at ./loading.jl:852
│  [17] macro expansion at ./logging.jl:311 [inlined]
│  [18] require(::Module, ::Symbol) at ./loading.jl:834
│  [19] eval(::Module, ::Any) at ./boot.jl:319
│  [20] eval_user_input(::Any, ::REPL.REPLBackend) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/REPL/src/REPL.jl:85
│  [21] macro expansion at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/REPL/src/REPL.jl:117 [inlined]
│  [22] (::getfield(REPL, Symbol("##28#29")){REPL.REPLBackend})() at ./task.jl:259
└ @ Requires ~/.julia/packages/Requires/9Jse/src/require.jl:40

```

Project:

```toml
[deps]
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
```

Manifest:

```toml
[[Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"

[[BinDeps]]
deps = ["Compat", "Libdl", "SHA", "URIParser"]
git-tree-sha1 = "12093ca6cdd0ee547c39b1870e0c9c3f154d9ca9"
uuid = "9e28174c-4ba2-5203-b857-d8d62c4213ee"
version = "0.8.10"

[[BinaryProvider]]
deps = ["Libdl", "Pkg", "SHA", "Test"]
git-tree-sha1 = "b530fbeb6f41ab5a83fbe3db1fcbe879334bcd2d"
uuid = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
version = "0.4.2"

[[Calculus]]
deps = ["Compat"]
git-tree-sha1 = "f60954495a7afcee4136f78d1d60350abd37a409"
uuid = "49dc2e85-a5d0-5ad3-a950-438e2897f1b9"
version = "0.4.1"

[[Compat]]
deps = ["Base64", "Dates", "DelimitedFiles", "Distributed", "InteractiveUtils", "LibGit2", "Libdl", "LinearAlgebra", "Markdown", "Mmap", "Pkg", "Printf", "REPL", "Random", "Serialization", "SharedArrays", "Sockets", "SparseArrays", "Statistics", "Test", "UUIDs", "Unicode"]
git-tree-sha1 = "ae262fa91da6a74e8937add6b613f58cd56cdad4"
uuid = "34da2185-b29b-5c13-b0c7-acf172513d20"
version = "1.1.0"

[[DataStructures]]
deps = ["InteractiveUtils", "REPL", "Random", "Serialization", "Test"]
git-tree-sha1 = "2afbbd0294306b0b74a753c196be50b35edb625c"
uuid = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
version = "0.11.1"

[[Dates]]
deps = ["Printf"]
uuid = "ade2ca70-3891-5945-98fb-dc099432e06a"

[[DelimitedFiles]]
deps = ["Mmap"]
uuid = "8bb1440f-4735-579b-a4ab-409b98df4dab"

[[DiffEqBase]]
deps = ["Compat", "IteratorInterfaceExtensions", "LinearAlgebra", "Pkg", "RecipesBase", "RecursiveArrayTools", "Requires", "StaticArrays", "Statistics", "TableTraits", "Test", "TreeViews"]
git-tree-sha1 = "508aff5d492a050433f731f3f71bf2e78c9e319c"
uuid = "2b5f629d-d688-5b77-993f-72d75c75574e"
version = "4.24.0"

[[Distributed]]
deps = ["LinearAlgebra", "Random", "Serialization", "Sockets"]
uuid = "8ba89e20-285c-5b6f-9357-94700520ee1b"

[[InteractiveUtils]]
deps = ["LinearAlgebra", "Markdown"]
uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[[IteratorInterfaceExtensions]]
deps = ["Test"]
git-tree-sha1 = "5484e5ede2a4137b9643f4d646e8e7b87b794415"
uuid = "82899510-4779-5014-852e-03e436cf321d"
version = "0.1.1"

[[LibGit2]]
uuid = "76f85450-5226-5b5a-8eaa-529ad045b433"

[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[LinearAlgebra]]
deps = ["Libdl"]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[[Logging]]
uuid = "56ddb016-857b-54e1-b83d-db4d58db5568"

[[Markdown]]
deps = ["Base64"]
uuid = "d6f4376e-aef5-505a-96c1-9c027394607a"

[[Measurements]]
deps = ["Calculus", "LinearAlgebra", "Pkg", "QuadGK", "RecipesBase", "Requires", "SpecialFunctions", "Statistics", "Test"]
git-tree-sha1 = "5d4745b25566c59239c21b8db83d27ef27ee7a33"
uuid = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
version = "1.0.0"

[[Mmap]]
uuid = "a63ad114-7e13-5084-954f-fe012c677804"

[[Pkg]]
deps = ["Dates", "LibGit2", "Markdown", "Printf", "REPL", "Random", "SHA", "UUIDs"]
uuid = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[[Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[[QuadGK]]
deps = ["DataStructures", "LinearAlgebra", "Test"]
git-tree-sha1 = "7d61ca207f021be6574b365a1a077bea04935f19"
uuid = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
version = "2.0.1"

[[REPL]]
deps = ["InteractiveUtils", "Markdown", "Sockets"]
uuid = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[[Random]]
deps = ["Serialization"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[RecipesBase]]
deps = ["Pkg", "Random", "Test"]
git-tree-sha1 = "0b3cb370ee4dc00f47f1193101600949f3dcf884"
uuid = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
version = "0.6.0"

[[RecursiveArrayTools]]
deps = ["RecipesBase", "Requires", "StaticArrays", "Statistics", "Test"]
git-tree-sha1 = "797075ed835f708dec7a8475c67657abdccfd0b3"
uuid = "731186ca-8d62-57ce-b412-fbd966d074cd"
version = "0.18.0"

[[Requires]]
deps = ["Test"]
git-tree-sha1 = "f6fbf4ba64d295e146e49e021207993b6b48c7d1"
uuid = "ae029012-a4dd-5104-9daa-d747884805df"
version = "0.5.2"

[[SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[[Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[[SharedArrays]]
deps = ["Distributed", "Mmap", "Random", "Serialization"]
uuid = "1a1011a3-84de-559e-8e89-a11a2f7dc383"

[[Sockets]]
uuid = "6462fe0b-24de-5631-8697-dd941f90decc"

[[SparseArrays]]
deps = ["LinearAlgebra", "Random"]
uuid = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[[SpecialFunctions]]
deps = ["BinDeps", "BinaryProvider", "Compat", "Libdl"]
git-tree-sha1 = "d12f8917be3782f4b800ba16003b8d0d4858c2e5"
uuid = "276daf66-3868-5448-9aa4-cd146d93841b"
version = "0.7.0"

[[StaticArrays]]
deps = ["InteractiveUtils", "LinearAlgebra", "Random", "Statistics", "Test"]
git-tree-sha1 = "d432c79bef174a830304f8601427a4357dfdbfb7"
uuid = "90137ffa-7385-5640-81b9-e52037218182"
version = "0.8.3"

[[Statistics]]
deps = ["LinearAlgebra", "SparseArrays"]
uuid = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[[TableTraits]]
deps = ["IteratorInterfaceExtensions", "Test"]
git-tree-sha1 = "afee1fb3bc99c28eb4533ff0f22e33f6effcec18"
uuid = "3783bdb8-4a98-5b6b-af9a-565f29a5fe9c"
version = "0.3.1"

[[Test]]
deps = ["Distributed", "InteractiveUtils", "Logging", "Random"]
uuid = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[[TreeViews]]
deps = ["Test"]
git-tree-sha1 = "8d0d7a3fe2f30d6a7f833a5f19f7c7a5b396eae6"
uuid = "a2a6695c-b41b-5b7d-aed9-dbfdeacea5d7"
version = "0.3.0"

[[URIParser]]
deps = ["Test", "Unicode"]
git-tree-sha1 = "6ddf8244220dfda2f17539fa8c9de20d6c575b69"
uuid = "30578b45-9adc-5946-b283-645ec420af67"
version = "0.4.0"

[[UUIDs]]
deps = ["Random"]
uuid = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[[Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"
```
